// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pwPQehv5dRCmck24osLGTw
// Component: Tk2xyQel6ClW
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button from "../../Button"; // plasmic-import: YEbXEiVokJ6F/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: pwPQehv5dRCmck24osLGTw/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: Tk2xyQel6ClW/css
import SubtractIcon from "./icons/PlasmicIcon__Subtract"; // plasmic-import: MDoTlH2Xh3eu/icon
import HeartIcon from "./icons/PlasmicIcon__Heart"; // plasmic-import: e7qkCN3NBUu0/icon
import CartIcon from "./icons/PlasmicIcon__Cart"; // plasmic-import: XvKAHPgz-9Dl/icon
import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: V9FA4UKafOeV/icon
import Location2Icon from "./icons/PlasmicIcon__Location2"; // plasmic-import: rMYIo-GnlfK6/icon
import Vector14Icon from "./icons/PlasmicIcon__Vector14"; // plasmic-import: nXpw03loerny/icon
import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: 0A_Djc7hhrf6/icon
import Vector12Icon from "./icons/PlasmicIcon__Vector12"; // plasmic-import: 8eGtdzp2vDu8/icon
import Vector13Icon from "./icons/PlasmicIcon__Vector13"; // plasmic-import: 7jwFzd-VW_o-/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: In_oSzSwKXqs/icon
import Letter2Icon from "./icons/PlasmicIcon__Letter2"; // plasmic-import: CIMhv7NeZ8Cy/icon
import Ellipse5Icon from "./icons/PlasmicIcon__Ellipse5"; // plasmic-import: mcRldE_sA1fA/icon
import ArrowRightIcon from "./icons/PlasmicIcon__ArrowRight"; // plasmic-import: ni4mMk4rRtrq/icon
import Ellipse9Icon from "./icons/PlasmicIcon__Ellipse9"; // plasmic-import: yFYSWs37jspy/icon
import ArrowBackIcon from "./icons/PlasmicIcon__ArrowBack"; // plasmic-import: OBAQpz10zxCr/icon
import Rectangle76Icon from "./icons/PlasmicIcon__Rectangle76"; // plasmic-import: 9CClV-mg1ugT/icon
import LocationIcon from "./icons/PlasmicIcon__Location"; // plasmic-import: DTr1oUEcNL9H/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: ziFZt_LyiGn_/icon
import LetterIcon from "./icons/PlasmicIcon__Letter"; // plasmic-import: LfmTnDUMmVX0/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: dfIBTVQDquUU/icon
import imageBzRx2W80V260 from "./images/image.png"; // plasmic-import: bzRX2W80V260/picture
import image2H1ElReudrLvW from "./images/image2.png"; // plasmic-import: H1ElReudrLvW/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"figmaPaste"}
            data-plasmic-override={overrides.figmaPaste}
            className={classNames(projectcss.all, sty.figmaPaste)}
          >
            <div
              data-plasmic-name={"header2"}
              data-plasmic-override={overrides.header2}
              className={classNames(projectcss.all, sty.header2)}
            >
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(projectcss.all, sty.header)}
              >
                <SubtractIcon
                  className={classNames(projectcss.all, sty.svg__vQ3L6)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"rightPanel"}
                data-plasmic-override={overrides.rightPanel}
                className={classNames(projectcss.all, sty.rightPanel)}
              >
                <HeartIcon
                  className={classNames(projectcss.all, sty.svg__d4XEg)}
                  role={"img"}
                />

                <CartIcon
                  className={classNames(projectcss.all, sty.svg__mDDN)}
                  role={"img"}
                />

                <ProfileIcon
                  className={classNames(projectcss.all, sty.svg__edJl)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7OjtX
                  )}
                >
                  {
                    "\u041f\u0440\u043e\u0444\u0438\u043b\u044c                 \u041a\u043e\u0440\u0437\u0438\u043d\u0430                \u0418\u0437\u0431\u0440\u0430\u043d\u043d\u043e\u0435"
                  }
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__oOo8X)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToProfile"] = true
                      ? (() => {
                          const actionArgs = { destination: `/profile` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToProfile"] != null &&
                      typeof $steps["goToProfile"] === "object" &&
                      typeof $steps["goToProfile"].then === "function"
                    ) {
                      $steps["goToProfile"] = await $steps["goToProfile"];
                    }
                  }}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__hF7Mc)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToCart"] = true
                      ? (() => {
                          const actionArgs = { destination: `/cart` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToCart"] != null &&
                      typeof $steps["goToCart"] === "object" &&
                      typeof $steps["goToCart"].then === "function"
                    ) {
                      $steps["goToCart"] = await $steps["goToCart"];
                    }
                  }}
                />
              </div>
              <div
                data-plasmic-name={"logoText1"}
                data-plasmic-override={overrides.logoText1}
                className={classNames(projectcss.all, sty.logoText1)}
              />

              <div
                data-plasmic-name={"region"}
                data-plasmic-override={overrides.region}
                className={classNames(projectcss.all, sty.region)}
              >
                <Location2Icon
                  className={classNames(projectcss.all, sty.svg__iBhPn)}
                  role={"img"}
                />

                <Vector14Icon
                  className={classNames(projectcss.all, sty.svg___9QxJo)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={
                    "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438"
                  }
                  data-plasmic-override={overrides.регионДоставки}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.региондоставки
                  )}
                >
                  {
                    " \u0420\u0435\u0433\u0438\u043e\u043d \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438:\n"
                  }
                </div>
                <div
                  data-plasmic-name={
                    "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a"
                  }
                  data-plasmic-override={overrides.гВладивосток}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.гвладивосток
                  )}
                >
                  {
                    " \u0433. \u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a"
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"search"}
                data-plasmic-override={overrides.search}
                className={classNames(projectcss.all, sty.search)}
              >
                <div
                  data-plasmic-name={"rectangle1"}
                  data-plasmic-override={overrides.rectangle1}
                  className={classNames(projectcss.all, sty.rectangle1)}
                />

                <div
                  data-plasmic-name={"rectangle2"}
                  data-plasmic-override={overrides.rectangle2}
                  className={classNames(projectcss.all, sty.rectangle2)}
                />

                <SearchIcon
                  className={classNames(projectcss.all, sty.svg__vhDRa)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cozGr
                  )}
                >
                  {
                    "\u041f\u043e\u0438\u0441\u043a \u0442\u043e\u0432\u0430\u0440\u043e\u0432"
                  }
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"hits"}
              data-plasmic-override={overrides.hits}
              className={classNames(projectcss.all, sty.hits)}
            >
              <div
                data-plasmic-name={"item1"}
                data-plasmic-override={overrides.item1}
                className={classNames(projectcss.all, sty.item1)}
              >
                <div
                  data-plasmic-name={"rectangle6"}
                  data-plasmic-override={overrides.rectangle6}
                  className={classNames(projectcss.all, sty.rectangle6)}
                />

                <div
                  data-plasmic-name={"rectangle530"}
                  data-plasmic-override={overrides.rectangle530}
                  className={classNames(projectcss.all, sty.rectangle530)}
                />

                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__bReiB)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"image9"}
                  data-plasmic-override={overrides.image9}
                  className={classNames(projectcss.all, sty.image9)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tLm7O
                  )}
                >
                  {
                    "Calligrata, 2.0 \u043c\u043c, \u0447\u0435\u0440\u043d\u044b\u0439"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ehAFm
                  )}
                >
                  {
                    "\u041c\u0430\u0440\u043a\u0435\u0440 \u043f\u0435\u0440\u043c\u0430\u043d\u0435\u043d\u0442\u043d\u044b\u0439 \u0434\u0432\u0443\u0445\u0441\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fGXiY
                  )}
                >
                  {"39 \u20bd"}
                </div>
              </div>
              <div
                data-plasmic-name={"item2"}
                data-plasmic-override={overrides.item2}
                className={classNames(projectcss.all, sty.item2)}
              >
                <div
                  data-plasmic-name={"rectangle7"}
                  data-plasmic-override={overrides.rectangle7}
                  className={classNames(projectcss.all, sty.rectangle7)}
                >
                  <div
                    data-plasmic-name={"image10"}
                    data-plasmic-override={overrides.image10}
                    className={classNames(projectcss.all, sty.image10)}
                  />
                </div>
                <div
                  data-plasmic-name={"rectangle531"}
                  data-plasmic-override={overrides.rectangle531}
                  className={classNames(projectcss.all, sty.rectangle531)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__p4LWe
                  )}
                >
                  {
                    "Attache Glide Trigel, 0.5 \u043c\u043c, \u0441\u0438\u043d\u044f\u044f"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rsmhU
                  )}
                >
                  {
                    "\u0420\u0443\u0447\u043a\u0430 \u0433\u0435\u043b\u0435\u0432\u0430\u044f \u043d\u0435\u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8FhZp
                  )}
                >
                  {"23 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__fo4Ar)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item3"}
                data-plasmic-override={overrides.item3}
                className={classNames(projectcss.all, sty.item3)}
              >
                <div
                  data-plasmic-name={"rectangle8"}
                  data-plasmic-override={overrides.rectangle8}
                  className={classNames(projectcss.all, sty.rectangle8)}
                />

                <div
                  data-plasmic-name={"rectangle532"}
                  data-plasmic-override={overrides.rectangle532}
                  className={classNames(projectcss.all, sty.rectangle532)}
                />

                <div
                  data-plasmic-name={"image11"}
                  data-plasmic-override={overrides.image11}
                  className={classNames(projectcss.all, sty.image11)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5ULTe
                  )}
                >
                  {"\u041a\u043e\u043c\u0443\u0441 Grand-X, HB"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__meMX
                  )}
                >
                  {
                    "\u041a\u0430\u0440\u0430\u043d\u0434\u0430\u0448 \u0447\u0435\u0440\u043d\u043e\u0433\u0440\u0430\u0444\u0438\u0442\u043d\u044b\u0439 \u0441 \u043b\u0430\u0441\u0442\u0438\u043a\u043e\u043c"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dfOqs
                  )}
                >
                  {"14 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__bpD5O)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item4"}
                data-plasmic-override={overrides.item4}
                className={classNames(projectcss.all, sty.item4)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />

                <div
                  data-plasmic-name={"rectangle533"}
                  data-plasmic-override={overrides.rectangle533}
                  className={classNames(projectcss.all, sty.rectangle533)}
                />

                <div
                  data-plasmic-name={"image12"}
                  data-plasmic-override={overrides.image12}
                  className={classNames(projectcss.all, sty.image12)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__to9Yk
                  )}
                >
                  {"Hatber, 24 \u043b"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5JSb
                  )}
                >
                  {
                    "\u0422\u0435\u0442\u0440\u0430\u0434\u044c\n\u0432 \u043a\u043b\u0435\u0442\u043a\u0443"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nblWp
                  )}
                >
                  {"29 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__shpQs)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item5"}
                data-plasmic-override={overrides.item5}
                className={classNames(projectcss.all, sty.item5)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  data-plasmic-name={"rectangle534"}
                  data-plasmic-override={overrides.rectangle534}
                  className={classNames(projectcss.all, sty.rectangle534)}
                />

                <div
                  data-plasmic-name={"image13"}
                  data-plasmic-override={overrides.image13}
                  className={classNames(projectcss.all, sty.image13)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pppxI
                  )}
                >
                  {"Goodmark, 21.5 \u0441\u043c"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bw8At
                  )}
                >
                  {
                    "\u041d\u043e\u0436\u043d\u0438\u0446\u044b\n\u043e\u0444\u0438\u0441\u043d\u044b\u0435"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__inbMw
                  )}
                >
                  {"189 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__mD836)}
                  role={"img"}
                />
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dbZoP
                )}
              >
                {
                  "\u0425\u0438\u0442\u044b \u043f\u0440\u043e\u0434\u0430\u0436"
                }
              </div>
              <Vector13Icon
                className={classNames(projectcss.all, sty.svg__umX)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"_new"}
              data-plasmic-override={overrides._new}
              className={classNames(projectcss.all, sty._new)}
            >
              <div
                data-plasmic-name={"item12"}
                data-plasmic-override={overrides.item12}
                className={classNames(projectcss.all, sty.item12)}
              >
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"rectangle535"}
                  data-plasmic-override={overrides.rectangle535}
                  className={classNames(projectcss.all, sty.rectangle535)}
                />

                <div
                  data-plasmic-name={"image14"}
                  data-plasmic-override={overrides.image14}
                  className={classNames(projectcss.all, sty.image14)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tkZu8
                  )}
                >
                  {"SvetoCopy ECO, \u04104, 500 \u043b"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y5H5A
                  )}
                >
                  {
                    "\u0411\u0443\u043c\u0430\u0433\u0430 \u0434\u043b\u044f \u043e\u0444\u0438\u0441\u043d\u043e\u0439 \u0442\u0435\u0445\u043d\u0438\u043a\u0438"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w29Qn
                  )}
                >
                  {"329 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg___20TA5)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item22"}
                data-plasmic-override={overrides.item22}
                className={classNames(projectcss.all, sty.item22)}
              >
                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  data-plasmic-name={"rectangle536"}
                  data-plasmic-override={overrides.rectangle536}
                  className={classNames(projectcss.all, sty.rectangle536)}
                />

                <div
                  data-plasmic-name={"image15"}
                  data-plasmic-override={overrides.image15}
                  className={classNames(projectcss.all, sty.image15)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7MhzS
                  )}
                >
                  {
                    "\u041a\u043e\u043c\u0443\u0441 \u04104, \u0434\u043e 100 \u043b\u0438\u0441\u0442\u043e\u0432, \u0447\u0435\u0440\u043d\u044b\u0439"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qnonw
                  )}
                >
                  {
                    "\u0421\u043a\u043e\u0440\u043e\u0441\u0448\u0438\u0432\u0430\u0442\u0435\u043b\u044c \u043f\u043b\u0430\u0441\u0442\u0438\u043a\u043e\u0432\u044b\u0439"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hzT0
                  )}
                >
                  {"39 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg___5KE8G)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item32"}
                data-plasmic-override={overrides.item32}
                className={classNames(projectcss.all, sty.item32)}
              >
                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />

                <div
                  data-plasmic-name={"rectangle537"}
                  data-plasmic-override={overrides.rectangle537}
                  className={classNames(projectcss.all, sty.rectangle537)}
                />

                <div
                  data-plasmic-name={"image16"}
                  data-plasmic-override={overrides.image16}
                  className={classNames(projectcss.all, sty.image16)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y7Wg3
                  )}
                >
                  {
                    "Attache \u04104, \u0434\u043e 60 \u0444\u0430\u0439\u043b\u043e\u0432, \u0441\u0438\u043d\u044f\u044f"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___552ZY
                  )}
                >
                  {
                    "\u041f\u0430\u043f\u043a\u0430\n\u0444\u0430\u0439\u043b\u043e\u0432\u0430\u044f"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Ue9Q
                  )}
                >
                  {"275 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__w4AKe)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item42"}
                data-plasmic-override={overrides.item42}
                className={classNames(projectcss.all, sty.item42)}
              >
                <div
                  data-plasmic-name={"rectangle14"}
                  data-plasmic-override={overrides.rectangle14}
                  className={classNames(projectcss.all, sty.rectangle14)}
                />

                <div
                  data-plasmic-name={"rectangle538"}
                  data-plasmic-override={overrides.rectangle538}
                  className={classNames(projectcss.all, sty.rectangle538)}
                />

                <div
                  data-plasmic-name={"image17"}
                  data-plasmic-override={overrides.image17}
                  className={classNames(projectcss.all, sty.image17)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hVsb
                  )}
                >
                  {"Attache, 5 \u043c\u043c x 13 \u043c"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5141E
                  )}
                >
                  {
                    "\u041a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u0443\u044e\u0449\u0430\u044f\n\u043b\u0435\u043d\u0442\u0430"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vBzRo
                  )}
                >
                  {"199 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg__bz6Wu)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"item52"}
                data-plasmic-override={overrides.item52}
                className={classNames(projectcss.all, sty.item52)}
              >
                <div
                  data-plasmic-name={"rectangle15"}
                  data-plasmic-override={overrides.rectangle15}
                  className={classNames(projectcss.all, sty.rectangle15)}
                />

                <div
                  data-plasmic-name={"rectangle539"}
                  data-plasmic-override={overrides.rectangle539}
                  className={classNames(projectcss.all, sty.rectangle539)}
                />

                <div
                  data-plasmic-name={"image18"}
                  data-plasmic-override={overrides.image18}
                  className={classNames(projectcss.all, sty.image18)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zQFwf
                  )}
                >
                  {"Attache\u00a0Economy, 30 \u0441\u043c"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eAw5K
                  )}
                >
                  {
                    "\u041b\u0438\u043d\u0435\u0439\u043a\u0430\n\u043f\u043b\u0430\u0441\u0442\u0438\u043a\u043e\u0432\u0430\u044f"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zC3X
                  )}
                >
                  {"32 \u20bd"}
                </div>
                <Vector12Icon
                  className={classNames(projectcss.all, sty.svg___9Ebf9)}
                  role={"img"}
                />
              </div>
              <Button
                data-plasmic-name={"showMore"}
                data-plasmic-override={overrides.showMore}
                className={classNames("__wab_instance", sty.showMore)}
                flatSide={[]}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ozNqJ
                    )}
                  >
                    {
                      "\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0431\u043e\u043b\u044c\u0448\u0435"
                    }
                  </div>
                }
                onClick={async event => {
                  const $steps = {};
                  $steps["updateStateVariable"] = true
                    ? (() => {
                        const actionArgs = {};
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateStateVariable"] != null &&
                    typeof $steps["updateStateVariable"] === "object" &&
                    typeof $steps["updateStateVariable"].then === "function"
                  ) {
                    $steps["updateStateVariable"] = await $steps[
                      "updateStateVariable"
                    ];
                  }
                }}
                roundedFull={true}
                type={"soft"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8A8W
                )}
              >
                {"\u041d\u043e\u0432\u0438\u043d\u043a\u0438"}
              </div>
              <Vector13Icon
                className={classNames(projectcss.all, sty.svg__b7CC1)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"loyaltyClub"}
              data-plasmic-override={overrides.loyaltyClub}
              className={classNames(projectcss.all, sty.loyaltyClub)}
            >
              <div
                data-plasmic-name={"rectangle17"}
                data-plasmic-override={overrides.rectangle17}
                className={classNames(projectcss.all, sty.rectangle17)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yjhB2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: imageBzRx2W80V260,
                    fullWidth: 433,
                    fullHeight: 433,
                    aspectRatio: undefined
                  }}
                />

                <Button
                  data-plasmic-name={"clubButton"}
                  data-plasmic-override={overrides.clubButton}
                  className={classNames("__wab_instance", sty.clubButton)}
                  color={"muted"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6KMjI
                      )}
                    >
                      {
                        "\u0412\u0441\u0442\u0443\u043f\u0438\u0442\u044c \u0432 \u043a\u043b\u0443\u0431"
                      }
                    </div>
                  }
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateStateVariable"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;
                            undefined;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateStateVariable"] != null &&
                      typeof $steps["updateStateVariable"] === "object" &&
                      typeof $steps["updateStateVariable"].then === "function"
                    ) {
                      $steps["updateStateVariable"] = await $steps[
                        "updateStateVariable"
                      ];
                    }
                  }}
                  roundedFull={true}
                  type={"soft"}
                />
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r1B9J
                )}
              >
                {
                  "\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430 \u043b\u043e\u044f\u043b\u044c\u043d\u043e\u0441\u0442\u0438"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__guEh7
                )}
              >
                {
                  "\u0417\u0430\u0440\u0430\u0431\u0430\u0442\u044b\u0432\u0430\u0439\u0442\u0435 \u0431\u0430\u043b\u043b\u044b \u0438 \u043f\u043e\u043b\u0443\u0447\u0430\u0439\u0442\u0435 \u043f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430"
                }
              </div>
            </div>
            <div
              data-plasmic-name={"rassilka"}
              data-plasmic-override={overrides.rassilka}
              className={classNames(projectcss.all, sty.rassilka)}
            >
              <div
                data-plasmic-name={"rectangle19"}
                data-plasmic-override={overrides.rectangle19}
                className={classNames(projectcss.all, sty.rectangle19)}
              >
                <div
                  data-plasmic-name={"send1"}
                  data-plasmic-override={overrides.send1}
                  className={classNames(projectcss.all, sty.send1)}
                />
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rxHd6
                )}
              >
                {
                  "\u041f\u043e\u0434\u043f\u0438\u0441\u044b\u0432\u0430\u0439\u0442\u0435\u0441\u044c \u0438 \u043f\u043e\u043b\u0443\u0447\u0430\u0439\u0442\u0435 \u044d\u043a\u0441\u043b\u044e\u0437\u0438\u0432\u043d\u044b\u0435 \u0441\u043a\u0438\u0434\u043a\u0438"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__woyE5
                )}
              >
                {"\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430"}
              </div>
              <div
                data-plasmic-name={"rectangle20"}
                data-plasmic-override={overrides.rectangle20}
                className={classNames(projectcss.all, sty.rectangle20)}
              >
                <GroupIcon
                  className={classNames(projectcss.all, sty.svg__cNMl)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateStateVariable"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;
                            undefined;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateStateVariable"] != null &&
                      typeof $steps["updateStateVariable"] === "object" &&
                      typeof $steps["updateStateVariable"].then === "function"
                    ) {
                      $steps["updateStateVariable"] = await $steps[
                        "updateStateVariable"
                      ];
                    }
                  }}
                  role={"img"}
                />
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8G0R6
                )}
              >
                {"\u0412\u0430\u0448 e-mail"}
              </div>
              <Letter2Icon
                className={classNames(projectcss.all, sty.svg___2Jskx)}
                role={"img"}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zToW)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: image2H1ElReudrLvW,
                  fullWidth: 117,
                  fullHeight: 84,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"advert"}
              data-plasmic-override={overrides.advert}
              className={classNames(projectcss.all, sty.advert)}
            >
              <div
                data-plasmic-name={"advert1"}
                data-plasmic-override={overrides.advert1}
                className={classNames(projectcss.all, sty.advert1)}
              />

              <Ellipse5Icon
                className={classNames(projectcss.all, sty.svg__eTkQi)}
                role={"img"}
              />

              <Ellipse5Icon
                className={classNames(projectcss.all, sty.svg__qMdDf)}
                role={"img"}
              />

              <Ellipse5Icon
                className={classNames(projectcss.all, sty.svg__nerCd)}
                role={"img"}
              />

              <Ellipse5Icon
                className={classNames(projectcss.all, sty.svg__lmS)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle540"}
                data-plasmic-override={overrides.rectangle540}
                className={classNames(projectcss.all, sty.rectangle540)}
              />

              <ArrowRightIcon
                className={classNames(projectcss.all, sty.svg__vqBrC)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fk07G
                )}
              >
                {"\u041f\u041e\u0414\u0420\u041e\u0411\u041d\u0415\u0415"}
              </div>
              <Ellipse9Icon
                className={classNames(projectcss.all, sty.svg___4AZd3)}
                role={"img"}
              />

              <Ellipse9Icon
                className={classNames(projectcss.all, sty.svg__ynEaP)}
                role={"img"}
              />

              <ArrowBackIcon
                className={classNames(projectcss.all, sty.svg___0PqKe)}
                role={"img"}
              />

              <ArrowBackIcon
                className={classNames(projectcss.all, sty.svg__aHWg7)}
                role={"img"}
              />

              <div
                data-plasmic-name={"underHeader"}
                data-plasmic-override={overrides.underHeader}
                className={classNames(projectcss.all, sty.underHeader)}
              >
                <div
                  data-plasmic-name={"rectangle545"}
                  data-plasmic-override={overrides.rectangle545}
                  className={classNames(projectcss.all, sty.rectangle545)}
                />
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xn0Vf
                )}
              >
                {
                  "\u041f\u0438\u0441\u044c\u043c\u0435\u043d\u043d\u044b\u0435 \u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u043d\u043e\u0441\u0442\u0438           \u0411\u0443\u043c\u0430\u0436\u043d\u0430\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0446\u0438\u044f           \u041e\u0444\u0438\u0441\u043d\u044b\u0435 \u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u043d\u043e\u0441\u0442\u0438           \u0423\u0447\u0435\u0431\u043d\u044b\u0435 \u043f\u043e\u0441\u043e\u0431\u0438\u044f           \u0428\u043a\u043e\u043b\u044c\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442\u0438\u043b\u044c          \u0412\u0435\u0441\u044c \u043a\u0430\u0442\u0430\u043b\u043e\u0433"
                }
              </div>
            </div>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <Rectangle76Icon
                className={classNames(projectcss.all, sty.svg___2FJ1N)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__saJCa
                )}
              >
                {
                  "\u041e\u0431\u0440\u0430\u0442\u043d\u0430\u044f \u0441\u0432\u0437\u044f\u044c"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7On7Q
                )}
              >
                {
                  "\u0412 \u0438\u043d\u0442\u0435\u0440\u043d\u0435\u0442-\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0435"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xYdmB
                )}
              >
                {
                  "\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u0438 \u043e\u043f\u043b\u0430\u0442\u0430"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__de8Hn
                )}
              >
                {
                  "\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0438 \u043e\u0442\u0432\u0435\u0442\u044b"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dMDdp
                )}
              >
                {
                  "\u0425\u043e\u0442\u0438\u0442\u0435 \u0443 \u043d\u0430\u0441 \u0440\u0430\u0431\u043e\u0442\u0430\u0442\u044c?"
                }
              </div>
              <LocationIcon
                className={classNames(projectcss.all, sty.svg__uiYyP)}
                role={"img"}
              />

              <div
                data-plasmic-name={
                  "scatch\u0421\u0435\u0442\u044c\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432\u0423\u0441\u043f\u0435\u0448\u043d\u043e\u0420\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445\u0412\u043e\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435\u0418\u0414\u0440\u0443\u0433\u0438\u0445\u0413\u043e\u0440\u043e\u0434\u0430\u0445\u0420\u043e\u0441\u0441\u0438\u0438\u0410\u0415\u0449\u0451\u042d\u0442\u043e\u041a\u0440\u0443\u043f\u043d\u044b\u0439\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438"
                }
                data-plasmic-override={
                  overrides.scatchСетьМагазиновУспешноРаботающихВоВладивостокеИДругихГородахРоссииАЕщёЭтоКрупныйИнтернетМагазинКанцелярии
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.scatchсетьмагазиновуспешноработающихвовладивостокеидругихгородахроссииаещёэтокрупныйинтернетмагазинканцелярии
                )}
              >
                {
                  "\u00abScatch\u00bb \u2013 \u0441\u0435\u0442\u044c \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432, \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0440\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445 \u0432\u043e \u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435 \u0438 \u0434\u0440\u0443\u0433\u0438\u0445 \u0433\u043e\u0440\u043e\u0434\u0430\u0445 \u0420\u043e\u0441\u0441\u0438\u0438.\n\n\u0410 \u0435\u0449\u0451 \u044d\u0442\u043e \u2013 \u043a\u0440\u0443\u043f\u043d\u044b\u0439 \u0438\u043d\u0442\u0435\u0440\u043d\u0435\u0442-\u043c\u0430\u0433\u0430\u0437\u0438\u043d \u043a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438. "
                }
              </div>
              <div
                data-plasmic-name={
                  "\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432Scatch"
                }
                data-plasmic-override={overrides.магазинКанцтоваровScatch}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.магазинканцтоваровScatch
                )}
              >
                {
                  "\u041c\u0430\u0433\u0430\u0437\u0438\u043d \u043a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432 \u00abScatch\u00bb\n"
                }
              </div>
              <div
                data-plasmic-name={"youtube"}
                data-plasmic-override={overrides.youtube}
                className={classNames(projectcss.all, sty.youtube)}
              />

              <div
                data-plasmic-name={"whatsapp"}
                data-plasmic-override={overrides.whatsapp}
                className={classNames(projectcss.all, sty.whatsapp)}
              />

              <div
                data-plasmic-name={"telegram"}
                data-plasmic-override={overrides.telegram}
                className={classNames(projectcss.all, sty.telegram)}
              />

              <div
                data-plasmic-name={"rectangle544"}
                data-plasmic-override={overrides.rectangle544}
                className={classNames(projectcss.all, sty.rectangle544)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__clmdn
                )}
              >
                {"scatch.ru, 2024"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vs9ZK
                )}
              >
                {
                  "\u0412\u0441\u0435 \u043f\u0440\u0430\u0432\u0430 \u0437\u0430\u0449\u0438\u0449\u0435\u043d\u044b"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ehb4H
                )}
              >
                {"\u00a9"}
              </div>
              <div
                data-plasmic-name={
                  "\u0432\u041d\u0430\u0448\u0438\u0445\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445"
                }
                data-plasmic-override={overrides.вНашихМагазинах}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.внашихмагазинах
                )}
              >
                {
                  "\u0412 \u043d\u0430\u0448\u0438\u0445 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445\n"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rjsxo
                )}
              >
                {
                  "\u0410\u0434\u0440\u0435\u0441\u0430 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bBhN
                )}
              >
                {"\u041e \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__trubp
                )}
              >
                {"\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b"}
              </div>
              <div
                data-plasmic-name={"_89024731492"}
                data-plasmic-override={overrides._89024731492}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty._89024731492
                )}
              >
                {"8 (902) 473-14-92 "}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yoXV
                )}
              >
                {"support@scatch.ru"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t7Uvy
                )}
              >
                {
                  "\u0433. \u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a, \u041b\u0435\u043d\u0438\u043d\u0430 46/1"
                }
              </div>
              <VectorIcon
                className={classNames(projectcss.all, sty.svg__sKmLd)}
                role={"img"}
              />

              <LetterIcon
                className={classNames(projectcss.all, sty.svg__f2Uk8)}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__vAfF)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "figmaPaste",
    "header2",
    "header",
    "rightPanel",
    "logoText1",
    "region",
    "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438",
    "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a",
    "search",
    "rectangle1",
    "rectangle2",
    "hits",
    "item1",
    "rectangle6",
    "rectangle530",
    "image9",
    "item2",
    "rectangle7",
    "image10",
    "rectangle531",
    "item3",
    "rectangle8",
    "rectangle532",
    "image11",
    "item4",
    "rectangle9",
    "rectangle533",
    "image12",
    "item5",
    "rectangle10",
    "rectangle534",
    "image13",
    "_new",
    "item12",
    "rectangle11",
    "rectangle535",
    "image14",
    "item22",
    "rectangle12",
    "rectangle536",
    "image15",
    "item32",
    "rectangle13",
    "rectangle537",
    "image16",
    "item42",
    "rectangle14",
    "rectangle538",
    "image17",
    "item52",
    "rectangle15",
    "rectangle539",
    "image18",
    "showMore",
    "loyaltyClub",
    "rectangle17",
    "clubButton",
    "rassilka",
    "rectangle19",
    "send1",
    "rectangle20",
    "advert",
    "advert1",
    "rectangle540",
    "underHeader",
    "rectangle545",
    "footer",
    "scatch\u0421\u0435\u0442\u044c\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432\u0423\u0441\u043f\u0435\u0448\u043d\u043e\u0420\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445\u0412\u043e\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435\u0418\u0414\u0440\u0443\u0433\u0438\u0445\u0413\u043e\u0440\u043e\u0434\u0430\u0445\u0420\u043e\u0441\u0441\u0438\u0438\u0410\u0415\u0449\u0451\u042d\u0442\u043e\u041a\u0440\u0443\u043f\u043d\u044b\u0439\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438",
    "\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432Scatch",
    "youtube",
    "whatsapp",
    "telegram",
    "rectangle544",
    "\u0432\u041d\u0430\u0448\u0438\u0445\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445",
    "_89024731492"
  ],

  figmaPaste: [
    "figmaPaste",
    "header2",
    "header",
    "rightPanel",
    "logoText1",
    "region",
    "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438",
    "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a",
    "search",
    "rectangle1",
    "rectangle2",
    "hits",
    "item1",
    "rectangle6",
    "rectangle530",
    "image9",
    "item2",
    "rectangle7",
    "image10",
    "rectangle531",
    "item3",
    "rectangle8",
    "rectangle532",
    "image11",
    "item4",
    "rectangle9",
    "rectangle533",
    "image12",
    "item5",
    "rectangle10",
    "rectangle534",
    "image13",
    "_new",
    "item12",
    "rectangle11",
    "rectangle535",
    "image14",
    "item22",
    "rectangle12",
    "rectangle536",
    "image15",
    "item32",
    "rectangle13",
    "rectangle537",
    "image16",
    "item42",
    "rectangle14",
    "rectangle538",
    "image17",
    "item52",
    "rectangle15",
    "rectangle539",
    "image18",
    "showMore",
    "loyaltyClub",
    "rectangle17",
    "clubButton",
    "rassilka",
    "rectangle19",
    "send1",
    "rectangle20",
    "advert",
    "advert1",
    "rectangle540",
    "underHeader",
    "rectangle545",
    "footer",
    "scatch\u0421\u0435\u0442\u044c\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432\u0423\u0441\u043f\u0435\u0448\u043d\u043e\u0420\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445\u0412\u043e\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435\u0418\u0414\u0440\u0443\u0433\u0438\u0445\u0413\u043e\u0440\u043e\u0434\u0430\u0445\u0420\u043e\u0441\u0441\u0438\u0438\u0410\u0415\u0449\u0451\u042d\u0442\u043e\u041a\u0440\u0443\u043f\u043d\u044b\u0439\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438",
    "\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432Scatch",
    "youtube",
    "whatsapp",
    "telegram",
    "rectangle544",
    "\u0432\u041d\u0430\u0448\u0438\u0445\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445",
    "_89024731492"
  ],

  header2: [
    "header2",
    "header",
    "rightPanel",
    "logoText1",
    "region",
    "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438",
    "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a",
    "search",
    "rectangle1",
    "rectangle2"
  ],

  header: ["header"],
  rightPanel: ["rightPanel"],
  logoText1: ["logoText1"],
  region: [
    "region",
    "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438",
    "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a"
  ],

  регионДоставки: [
    "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438"
  ],

  гВладивосток: [
    "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a"
  ],

  search: ["search", "rectangle1", "rectangle2"],
  rectangle1: ["rectangle1"],
  rectangle2: ["rectangle2"],
  hits: [
    "hits",
    "item1",
    "rectangle6",
    "rectangle530",
    "image9",
    "item2",
    "rectangle7",
    "image10",
    "rectangle531",
    "item3",
    "rectangle8",
    "rectangle532",
    "image11",
    "item4",
    "rectangle9",
    "rectangle533",
    "image12",
    "item5",
    "rectangle10",
    "rectangle534",
    "image13"
  ],

  item1: ["item1", "rectangle6", "rectangle530", "image9"],
  rectangle6: ["rectangle6"],
  rectangle530: ["rectangle530"],
  image9: ["image9"],
  item2: ["item2", "rectangle7", "image10", "rectangle531"],
  rectangle7: ["rectangle7", "image10"],
  image10: ["image10"],
  rectangle531: ["rectangle531"],
  item3: ["item3", "rectangle8", "rectangle532", "image11"],
  rectangle8: ["rectangle8"],
  rectangle532: ["rectangle532"],
  image11: ["image11"],
  item4: ["item4", "rectangle9", "rectangle533", "image12"],
  rectangle9: ["rectangle9"],
  rectangle533: ["rectangle533"],
  image12: ["image12"],
  item5: ["item5", "rectangle10", "rectangle534", "image13"],
  rectangle10: ["rectangle10"],
  rectangle534: ["rectangle534"],
  image13: ["image13"],
  _new: [
    "_new",
    "item12",
    "rectangle11",
    "rectangle535",
    "image14",
    "item22",
    "rectangle12",
    "rectangle536",
    "image15",
    "item32",
    "rectangle13",
    "rectangle537",
    "image16",
    "item42",
    "rectangle14",
    "rectangle538",
    "image17",
    "item52",
    "rectangle15",
    "rectangle539",
    "image18",
    "showMore"
  ],

  item12: ["item12", "rectangle11", "rectangle535", "image14"],
  rectangle11: ["rectangle11"],
  rectangle535: ["rectangle535"],
  image14: ["image14"],
  item22: ["item22", "rectangle12", "rectangle536", "image15"],
  rectangle12: ["rectangle12"],
  rectangle536: ["rectangle536"],
  image15: ["image15"],
  item32: ["item32", "rectangle13", "rectangle537", "image16"],
  rectangle13: ["rectangle13"],
  rectangle537: ["rectangle537"],
  image16: ["image16"],
  item42: ["item42", "rectangle14", "rectangle538", "image17"],
  rectangle14: ["rectangle14"],
  rectangle538: ["rectangle538"],
  image17: ["image17"],
  item52: ["item52", "rectangle15", "rectangle539", "image18"],
  rectangle15: ["rectangle15"],
  rectangle539: ["rectangle539"],
  image18: ["image18"],
  showMore: ["showMore"],
  loyaltyClub: ["loyaltyClub", "rectangle17", "clubButton"],
  rectangle17: ["rectangle17", "clubButton"],
  clubButton: ["clubButton"],
  rassilka: ["rassilka", "rectangle19", "send1", "rectangle20"],
  rectangle19: ["rectangle19", "send1"],
  send1: ["send1"],
  rectangle20: ["rectangle20"],
  advert: ["advert", "advert1", "rectangle540", "underHeader", "rectangle545"],
  advert1: ["advert1"],
  rectangle540: ["rectangle540"],
  underHeader: ["underHeader", "rectangle545"],
  rectangle545: ["rectangle545"],
  footer: [
    "footer",
    "scatch\u0421\u0435\u0442\u044c\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432\u0423\u0441\u043f\u0435\u0448\u043d\u043e\u0420\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445\u0412\u043e\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435\u0418\u0414\u0440\u0443\u0433\u0438\u0445\u0413\u043e\u0440\u043e\u0434\u0430\u0445\u0420\u043e\u0441\u0441\u0438\u0438\u0410\u0415\u0449\u0451\u042d\u0442\u043e\u041a\u0440\u0443\u043f\u043d\u044b\u0439\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438",
    "\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432Scatch",
    "youtube",
    "whatsapp",
    "telegram",
    "rectangle544",
    "\u0432\u041d\u0430\u0448\u0438\u0445\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445",
    "_89024731492"
  ],

  scatchСетьМагазиновУспешноРаботающихВоВладивостокеИДругихГородахРоссииАЕщёЭтоКрупныйИнтернетМагазинКанцелярии:
    [
      "scatch\u0421\u0435\u0442\u044c\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432\u0423\u0441\u043f\u0435\u0448\u043d\u043e\u0420\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445\u0412\u043e\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435\u0418\u0414\u0440\u0443\u0433\u0438\u0445\u0413\u043e\u0440\u043e\u0434\u0430\u0445\u0420\u043e\u0441\u0441\u0438\u0438\u0410\u0415\u0449\u0451\u042d\u0442\u043e\u041a\u0440\u0443\u043f\u043d\u044b\u0439\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438"
    ],

  магазинКанцтоваровScatch: [
    "\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432Scatch"
  ],

  youtube: ["youtube"],
  whatsapp: ["whatsapp"],
  telegram: ["telegram"],
  rectangle544: ["rectangle544"],
  вНашихМагазинах: [
    "\u0432\u041d\u0430\u0448\u0438\u0445\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445"
  ],

  _89024731492: ["_89024731492"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    figmaPaste: makeNodeComponent("figmaPaste"),
    header2: makeNodeComponent("header2"),
    header: makeNodeComponent("header"),
    rightPanel: makeNodeComponent("rightPanel"),
    logoText1: makeNodeComponent("logoText1"),
    region: makeNodeComponent("region"),
    регионДоставки: makeNodeComponent(
      "\u0440\u0435\u0433\u0438\u043e\u043d\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0438"
    ),
    гВладивосток: makeNodeComponent(
      "\u0433\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a"
    ),
    search: makeNodeComponent("search"),
    rectangle1: makeNodeComponent("rectangle1"),
    rectangle2: makeNodeComponent("rectangle2"),
    hits: makeNodeComponent("hits"),
    item1: makeNodeComponent("item1"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle530: makeNodeComponent("rectangle530"),
    image9: makeNodeComponent("image9"),
    item2: makeNodeComponent("item2"),
    rectangle7: makeNodeComponent("rectangle7"),
    image10: makeNodeComponent("image10"),
    rectangle531: makeNodeComponent("rectangle531"),
    item3: makeNodeComponent("item3"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle532: makeNodeComponent("rectangle532"),
    image11: makeNodeComponent("image11"),
    item4: makeNodeComponent("item4"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle533: makeNodeComponent("rectangle533"),
    image12: makeNodeComponent("image12"),
    item5: makeNodeComponent("item5"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle534: makeNodeComponent("rectangle534"),
    image13: makeNodeComponent("image13"),
    _new: makeNodeComponent("_new"),
    item12: makeNodeComponent("item12"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle535: makeNodeComponent("rectangle535"),
    image14: makeNodeComponent("image14"),
    item22: makeNodeComponent("item22"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle536: makeNodeComponent("rectangle536"),
    image15: makeNodeComponent("image15"),
    item32: makeNodeComponent("item32"),
    rectangle13: makeNodeComponent("rectangle13"),
    rectangle537: makeNodeComponent("rectangle537"),
    image16: makeNodeComponent("image16"),
    item42: makeNodeComponent("item42"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle538: makeNodeComponent("rectangle538"),
    image17: makeNodeComponent("image17"),
    item52: makeNodeComponent("item52"),
    rectangle15: makeNodeComponent("rectangle15"),
    rectangle539: makeNodeComponent("rectangle539"),
    image18: makeNodeComponent("image18"),
    showMore: makeNodeComponent("showMore"),
    loyaltyClub: makeNodeComponent("loyaltyClub"),
    rectangle17: makeNodeComponent("rectangle17"),
    clubButton: makeNodeComponent("clubButton"),
    rassilka: makeNodeComponent("rassilka"),
    rectangle19: makeNodeComponent("rectangle19"),
    send1: makeNodeComponent("send1"),
    rectangle20: makeNodeComponent("rectangle20"),
    advert: makeNodeComponent("advert"),
    advert1: makeNodeComponent("advert1"),
    rectangle540: makeNodeComponent("rectangle540"),
    underHeader: makeNodeComponent("underHeader"),
    rectangle545: makeNodeComponent("rectangle545"),
    footer: makeNodeComponent("footer"),
    scatchСетьМагазиновУспешноРаботающихВоВладивостокеИДругихГородахРоссииАЕщёЭтоКрупныйИнтернетМагазинКанцелярии:
      makeNodeComponent(
        "scatch\u0421\u0435\u0442\u044c\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432\u0423\u0441\u043f\u0435\u0448\u043d\u043e\u0420\u0430\u0431\u043e\u0442\u0430\u044e\u0449\u0438\u0445\u0412\u043e\u0412\u043b\u0430\u0434\u0438\u0432\u043e\u0441\u0442\u043e\u043a\u0435\u0418\u0414\u0440\u0443\u0433\u0438\u0445\u0413\u043e\u0440\u043e\u0434\u0430\u0445\u0420\u043e\u0441\u0441\u0438\u0438\u0410\u0415\u0449\u0451\u042d\u0442\u043e\u041a\u0440\u0443\u043f\u043d\u044b\u0439\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0435\u043b\u044f\u0440\u0438\u0438"
      ),
    магазинКанцтоваровScatch: makeNodeComponent(
      "\u043c\u0430\u0433\u0430\u0437\u0438\u043d\u041a\u0430\u043d\u0446\u0442\u043e\u0432\u0430\u0440\u043e\u0432Scatch"
    ),
    youtube: makeNodeComponent("youtube"),
    whatsapp: makeNodeComponent("whatsapp"),
    telegram: makeNodeComponent("telegram"),
    rectangle544: makeNodeComponent("rectangle544"),
    вНашихМагазинах: makeNodeComponent(
      "\u0432\u041d\u0430\u0448\u0438\u0445\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430\u0445"
    ),
    _89024731492: makeNodeComponent("_89024731492"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Scatch",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
